// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlQueueManager;

namespace SqlQueueManager.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20200626192729_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("SqlQueueManager.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QueueItems");
                });
#pragma warning restore 612, 618
        }
    }
}
